version: '3'
services: 
  postgis:
    image: tonny2v/postgis
    container_name: postgis
    environment: 
      - POSTGRES_USER=tonny
      - POSTGRES_DB=gis
      - POSTGRES_PASS=password
      - ALLOW_IP_RANGE=0.0.0.0/0
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes: 
      - ./pgdata:/var/lib/postgresql/data/pgdata
    ports: 
      - 5433:5432