services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build . -f ubuntu/Dockerfile-20.04-LTS -t tonny2v/starter
  - docker push tonny2v/starter:latest
