version: '3'
services:
  flask:
    container_name: flask
    build:
      context: .
      dockerfile: Dockerfile
    image: tonny2v/flask
    volumes:
      - .:/app
    ports:
      - "8000:5000"

networks:
  mynet:
    driver: bridge
