name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo ${{ env.DOCKER_USERNAME }}
        echo ${{ env.DOCKER_PASSWORD }} | docker login -u ${{ env.DOCKER_USERNAME }} --password-stdin
        docker build . --file ubuntu/Dockerfile-20.04-LTS --tag tonny2v/starter:$(date +%s)
        docker push tonny2v/starter:$(date +%s)
